"""
编译期 HTML 嵌入脚本
用法: python embed_html.py <输入HTML文件> <输出C头文件>

将 HTML 文件转义为 C 字符串常量，可直接通过 PROGMEM 编译进固件。
"""

import sys
import os
import re


def html_to_c_array(html_path, output_path):
    """将 HTML 文件转换为 C 头文件中的 PROGMEM 字符串"""
    
    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()
    
    # 转义反斜杠和双引号
    # 对 HTML 特殊字符进行转义，使其能放入 C 字符串中
    escaped = html.replace('\\', '\\\\')
    escaped = escaped.replace('"', '\\"')
    
    # 替换 R"rawliteral(...)" 为 C 字符串
    # 如果 HTML 本身包含 )rawliteral 则不能用 R"rawliteral"
    # 所以我们直接用普通 C 字符串
    
    basename = os.path.splitext(os.path.basename(html_path))[0]
    var_name = basename.upper().replace('-', '_').replace('.', '_')
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(f'// Auto-generated from {os.path.basename(html_path)}\n')
        f.write(f'// Do not edit this file directly.\n')
        f.write(f'// Re-generate with: python embed_html.py {os.path.basename(html_path)} {os.path.basename(output_path)}\n\n')
        f.write(f'#ifndef EMBEDDED_{var_name}_H\n')
        f.write(f'#define EMBEDDED_{var_name}_H\n\n')
        f.write(f'#include <Arduino.h>\n\n')
        f.write(f'static const char INDEX_HTML[] PROGMEM = R"rawliteral(\n')
        f.write(html)
        f.write('\n)rawliteral";\n\n')
        f.write(f'#endif // EMBEDDED_{var_name}_H\n')
    
    print(f"[embed] {html_path} → {output_path}")
    print(f"[embed] HTML size: {len(html)} bytes → {len(escaped)} chars (no escaping needed with rawliteral)")


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("用法: python embed_html.py <输入.html> <输出.h>")
        sys.exit(1)
    
    html_path = sys.argv[1]
    output_path = sys.argv[2]
    
    if not os.path.exists(html_path):
        print(f"错误: 找不到文件 {html_path}")
        sys.exit(1)
    
    html_to_c_array(html_path, output_path)
