// Auto-generated from web_config.html
// Do not edit this file directly.
// Re-generate with: python embed_html.py web_config.html webpage.h

#ifndef EMBEDDED_WEB_CONFIG_H
#define EMBEDDED_WEB_CONFIG_H

#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BLE Dongle 配置</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f0f2f5;color:#1a1a2e;padding:20px;max-width:720px;margin:0 auto}
h1{text-align:center;color:#1a73e8;font-size:22px;margin:16px 0 20px}
.card{background:#fff;border-radius:12px;padding:20px;margin-bottom:16px;box-shadow:0 2px 8px rgba(0,0,0,.08)}
.card h2{font-size:17px;margin-bottom:14px;color:#333;padding-bottom:8px;border-bottom:1px solid #eee}
.form-row{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:12px}
.form-group{flex:1;min-width:140px}
.form-group label{display:block;font-size:13px;margin-bottom:4px;color:#666;font-weight:500}
.form-group input,.form-group select{width:100%;padding:8px 10px;border:1px solid #ddd;border-radius:8px;font-size:14px;background:#fafafa;transition:border .2s}
.form-group input:focus,.form-group select:focus{outline:none;border-color:#1a73e8;background:#fff}
.hint{font-size:11px;color:#999;margin-top:3px}
.btn{padding:9px 18px;border:none;border-radius:8px;font-size:14px;cursor:pointer;color:#fff;transition:background .2s;display:inline-block}
.btn-primary{background:#1a73e8}
.btn-primary:hover{background:#1557b0}
.btn-success{background:#34a853}
.btn-success:hover{background:#2d9249}
.btn-danger{background:#ea4335}
.btn-danger:hover{background:#c5221f}
.btn-sm{padding:6px 12px;font-size:12px}
.action-bar{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
table{width:100%;border-collapse:collapse;margin-top:8px;font-size:14px}
th,td{padding:10px 8px;text-align:left;border-bottom:1px solid #eee}
th{color:#888;font-weight:600;font-size:13px}
tr:hover{background:#f8f9fa}
.empty{color:#aaa;text-align:center;padding:24px;font-size:14px}
.tag{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;color:#fff;font-weight:500}
.t0{background:#1a73e8}
.t1{background:#34a853}
.t2{background:#f9ab00;color:#333}
.tab-bar{display:flex;gap:4px;margin-bottom:16px;background:#e8e8e8;border-radius:10px;padding:3px}
.tab{flex:1;text-align:center;padding:10px;border-radius:8px;font-size:14px;cursor:pointer;transition:all .2s;color:#666;font-weight:500}
.tab.act{background:#1a73e8;color:#fff;box-shadow:0 2px 6px rgba(26,115,232,.3)}
.tab:hover:not(.act){background:#ddd}
.panel{display:none}
.panel.act{display:block}
</style>
</head>
<body>
<h1>🔧 BLE Dongle v2 配置</h1>

<!-- 模式选择 -->
<div class="card">
  <h2>🎛 设备工作模式</h2>
  <div class="tab-bar" id="modeTabs">
    <div class="tab act" data-mode="0" onclick="switchMode(0)">📡 扫描器</div>
    <div class="tab" data-mode="1" onclick="switchMode(1)">📢 模拟广播</div>
    <div class="tab" data-mode="2" onclick="switchMode(2)">🔗 串口透传</div>
  </div>
  <p style="font-size:12px;color:#999;margin-top:4px">保存后重启设备将按所选模式运行。串口透传暂未实现。</p>
</div>

<!-- ====== 面板：扫描器 ====== -->
<div class="panel act" id="panel0">
<div class="card">
  <h2>📡 BLE 扫描参数</h2>
  <div class="form-row">
    <div class="form-group"><label>扫描间隔 (0.625ms)</label><input type="number" id="si" value="100" min="4" max="16384"><div class="hint">默认 100 (≈62.5ms)</div></div>
    <div class="form-group"><label>扫描窗口 (0.625ms)</label><input type="number" id="sw" value="99" min="4" max="16384"><div class="hint">&le; 扫描间隔</div></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>扫描类型</label><select id="st"><option value="0">被动扫描</option><option value="1" selected>主动扫描</option></select></div>
    <div class="form-group"><label>过滤重复</label><select id="sd"><option value="0" selected>不过滤</option><option value="1">过滤重复</option></select></div>
  </div>
</div>

<div class="card">
  <h2>📋 白名单规则</h2>
  <div class="form-row">
    <div class="form-group" style="flex:0.7"><label>类型</label><select id="ft"><option value="0">MAC 地址</option><option value="1">广播名称</option><option value="2">厂商 ID</option></select></div>
    <div class="form-group" id="vg" style="flex:1.3"><label>值</label><input type="text" id="fv" placeholder="AA:BB:CC:DD:EE:FF"></div>
    <div class="form-group" id="cg" style="display:none;flex:0.8"><label>厂商 ID（HEX）</label><input type="text" id="ci" placeholder="0059" maxlength="6"><div class="hint">如 0059、4C00</div></div>
  </div>
  <button class="btn btn-primary" onclick="addEntry()">➕ 添加规则</button>
  <table><thead><tr><th>类型</th><th>值</th><th>状态</th><th>操作</th></tr></thead>
    <tbody id="wt"><tr><td colspan="4" class="empty">暂无白名单规则</td></tr></tbody></table>
</div>
</div>

<!-- ====== 面板：模拟广播 ====== -->
<div class="panel" id="panel1">
<div class="card">
  <h2>📢 广播参数</h2>
  <div class="form-row">
    <div class="form-group"><label>自定义 MAC</label><input type="text" id="am" placeholder="留空=默认 MAC"><div class="hint">格式 AA:BB:CC:DD:EE:FF</div></div>
    <div class="form-group"><label>广播类型</label><select id="at"><option value="0">ADV_IND（可连接）</option><option value="2">ADV_SCAN_IND</option><option value="3">ADV_NONCONN_IND</option></select></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>广播间隔 (0.625ms)</label><input type="number" id="ai" value="100" min="20" max="4000"><div class="hint">范围 20~4000，默认 100 (≈62.5ms)，即 12.5ms~2.5s</div></div>
    <div class="form-group"><label>发射功率</label><select id="ap"><option value="-12">-12 dBm</option><option value="-9">-9 dBm</option><option value="-6">-6 dBm</option><option value="-3">-3 dBm</option><option value="0" selected>0 dBm</option><option value="3">3 dBm</option><option value="6">6 dBm</option><option value="9">9 dBm</option></select></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>广播时长（秒）</label><input type="number" id="ad" value="0" min="0" max="3600"><div class="hint">0=持续广播</div></div>

  </div>
  <div class="form-row"><div class="form-group" style="flex:2"><label>广播数据（HEX）</label><input type="text" id="ah" placeholder="如 02010603034C00"><div class="hint">不填则只广播设备名 BLE-Dongle-Adv</div></div></div>
  <div class="form-row" id="scanRespRow"><div class="form-group" style="flex:2"><label>扫描响应数据（HEX）</label><input type="text" id="as" placeholder="可选"><div class="hint">扫描时应答包的 HEX 数据。不可连接 / 不可扫描类型下无效</div></div></div>
</div>
</div>

<!-- ====== 面板：串口透传 ====== -->
<div class="panel" id="panel2">
<div class="card"><h2>🔗 串口透传</h2><p style="color:#999;text-align:center;padding:32px">功能开发中，敬请期待...</p></div>
</div>

<!-- ====== 底部按钮 ====== -->
<div class="card"><div class="action-bar">
  <button class="btn btn-success" onclick="saveAll()">💾 保存全部配置</button>
  <button class="btn btn-danger" onclick="reboot()">🔄 重启设备</button>
</div></div>

<script>
var W=[],M=0;
function switchMode(m){M=m;document.querySelectorAll('.tab').forEach(function(t){t.classList.remove('act')});document.querySelectorAll('.panel').forEach(function(p){p.classList.remove('act')});document.querySelector('.tab[data-mode="'+m+'"]').classList.add('act');document.getElementById('panel'+m).classList.add('act')}

function loadConfig(){
  fetch('/api/config').then(function(r){return r.json()}).then(function(d){
    W=d.whitelist||[];renderTable();
    var dm=d.deviceMode!==undefined?d.deviceMode:0;M=dm;switchMode(dm);
    var sp=d.scanParams||{};
    document.getElementById('si').value=sp.scanInterval||100;
    document.getElementById('sw').value=sp.scanWindow||99;
    document.getElementById('st').value=sp.scanType||1;
    document.getElementById('sd').value=sp.scanDuplicate?1:0;
    var ap=d.advConfig||{};
    document.getElementById('am').value=ap.customMac||'';
    document.getElementById('ah').value=ap.advDataHex||'';
    document.getElementById('as').value=ap.scanRespHex||'';
    document.getElementById('ap').value=ap.txPower||0;
    document.getElementById('ai').value=ap.advInterval||100;
    document.getElementById('ad').value=ap.advDuration||0;
    document.getElementById('at').value=ap.advType||0;
    // 触发联动
    document.getElementById('at').dispatchEvent(new Event('change'));
  });
}

function renderTable(){
  var tb=document.getElementById('wt');
  if(!W.length){tb.innerHTML='<tr><td colspan="4" class="empty">暂无白名单规则</td></tr>';return}
  var L=['MAC','名称','厂商'],C=['t0','t1','t2'],h='';
  for(var i=0;i<W.length;i++){
    var e=W[i],v=e.type===2?'0x'+('0000'+e.companyId.toString(16).toUpperCase()).slice(-4):e.value;
    h+='<tr><td><span class="tag '+(C[e.type]||'')+'">'+(L[e.type]||'')+'</span></td><td>'+v+'</td><td>'+(e.enabled?'✅':'❌')+'</td><td><button class="btn btn-danger btn-sm" onclick="deleteEntry('+i+')">删除</button></td></tr>';
  }
  tb.innerHTML=h;
}

function addEntry(){
  var t=parseInt(document.getElementById('ft').value),v=document.getElementById('fv').value.trim(),c=document.getElementById('ci').value.trim();
  if(t===2){if(!c){alert('请输入厂商 ID（HEX）');return}var cid=parseInt(c,16);if(isNaN(cid)||cid<0||cid>65535){alert('无效 HEX');return}W.push({type:t,value:"",companyId:cid,enabled:true})}
  else{if(!v){alert('请输入值');return}W.push({type:t,value:v,companyId:0,enabled:true})}
  renderTable();document.getElementById('fv').value='';document.getElementById('ci').value='';
}

function deleteEntry(i){W.splice(i,1);renderTable()}

function saveAll(){
  var sp={scanInterval:parseInt(document.getElementById('si').value)||100,scanWindow:parseInt(document.getElementById('sw').value)||99,scanType:parseInt(document.getElementById('st').value)||1,scanDuplicate:document.getElementById('sd').value==='1',ownAddrType:0,scanFilterPolicy:0};
  var ap={customMac:document.getElementById('am').value.trim(),advDataHex:document.getElementById('ah').value.trim(),scanRespHex:document.getElementById('as').value.trim(),txPower:parseInt(document.getElementById('ap').value)||0,advInterval:parseInt(document.getElementById('ai').value)||100,advDuration:parseInt(document.getElementById('ad').value)||0,advType:parseInt(document.getElementById('at').value)||0};
  var payload={deviceMode:M,whitelist:W,scanParams:sp,advConfig:ap};
  fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json()}).then(function(){alert('✅ 保存成功，重启后生效')}).catch(function(){alert('❌ 保存失败')});
}

function reboot(){if(!confirm('确定重启设备？'))return;fetch('/api/reboot',{method:'POST'});alert('设备正在重启...')}

document.getElementById('ft').addEventListener('change',function(){var s=this.value==='2';document.getElementById('cg').style.display=s?'block':'none';document.getElementById('vg').style.display=s?'none':'block';if(!s)document.getElementById('fv').placeholder=this.value==='0'?'AA:BB:CC:DD:EE:FF':'广播名称'});

// 广播类型切换：不可连接/不可扫描类型禁用扫描响应数据
document.getElementById('at').addEventListener('change',function(){var t=parseInt(this.value);var disabled=(t===3);document.getElementById('as').disabled=disabled;document.getElementById('as').style.opacity=disabled?'0.4':'1';document.getElementById('scanRespRow').style.opacity=disabled?'0.5':'1'});

window.addEventListener('DOMContentLoaded',loadConfig);
</script>
</body>
</html>

)rawliteral";

#endif // EMBEDDED_WEB_CONFIG_H
