// Auto-generated from web_config.html
// Do not edit this file directly.
// Re-generate with: python embed_html.py web_config.html webpage.h

#ifndef EMBEDDED_WEB_CONFIG_H
#define EMBEDDED_WEB_CONFIG_H

#include <Arduino.h>

static const char INDEX_HTML[] PROGMEM = R"rawliteral(
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>BLE Dongle 配置</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;background:#f0f2f5;color:#1a1a2e;padding:20px;max-width:720px;margin:0 auto}
h1{text-align:center;color:#1a73e8;font-size:22px;margin:16px 0 20px}
.card{background:#fff;border-radius:12px;padding:20px;margin-bottom:16px;box-shadow:0 2px 8px rgba(0,0,0,.08)}
.card h2{font-size:17px;margin-bottom:14px;color:#333;padding-bottom:8px;border-bottom:1px solid #eee}
.form-row{display:flex;gap:12px;flex-wrap:wrap;margin-bottom:12px}
.form-group{flex:1;min-width:140px}
.form-group label{display:block;font-size:13px;margin-bottom:4px;color:#666;font-weight:500}
.form-group input,.form-group select{width:100%;padding:8px 10px;border:1px solid #ddd;border-radius:8px;font-size:14px;background:#fafafa;transition:border .2s}
.form-group input:focus,.form-group select:focus{outline:none;border-color:#1a73e8;background:#fff}
.hint{font-size:11px;color:#999;margin-top:3px}
.btn{padding:9px 18px;border:none;border-radius:8px;font-size:14px;cursor:pointer;color:#fff;transition:background .2s;display:inline-block}
.btn-primary{background:#1a73e8}
.btn-primary:hover{background:#1557b0}
.btn-success{background:#34a853}
.btn-success:hover{background:#2d9249}
.btn-danger{background:#ea4335}
.btn-danger:hover{background:#c5221f}
.btn-sm{padding:6px 12px;font-size:12px}
.action-bar{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}
table{width:100%;border-collapse:collapse;margin-top:8px;font-size:14px}
th,td{padding:10px 8px;text-align:left;border-bottom:1px solid #eee}
th{color:#888;font-weight:600;font-size:13px}
tr:hover{background:#f8f9fa}
.empty{color:#aaa;text-align:center;padding:24px;font-size:14px}
.tag{display:inline-block;padding:2px 8px;border-radius:10px;font-size:11px;font-weight:500;color:#fff;background:#555}
.t0{background:#1a73e8}
.t1{background:#34a853}
.t2{background:#f9ab00;color:#333}
.tab-bar{display:flex;gap:4px;margin-bottom:16px;background:#e8e8e8;border-radius:10px;padding:3px}
.tab{flex:1;text-align:center;padding:10px;border-radius:8px;font-size:14px;cursor:pointer;transition:all .2s;color:#666;font-weight:500}
.tab.act{background:#1a73e8;color:#fff;box-shadow:0 2px 6px rgba(26,115,232,.3)}
.tab:hover:not(.act){background:#ddd}
.panel{display:none}
.panel.act{display:block}
.bar{display:flex;align-items:center;gap:6px;padding:6px 10px;background:#f0fdf0;border-radius:8px;margin-bottom:8px;font-size:12px;color:#2a7d2a}
.bar.warn{background:#fff8e1;color:#996b00}
.bar.err{background:#ffeaea;color:#b30000}
.drag{cursor:grab;user-select:none}
.drag-icon{display:inline-block;margin-right:6px;color:#aaa;font-size:14px;cursor:grab;vertical-align:middle}
.drag-over td{background:#e8f0fe!important}
</style>
</head>
<body>
<h1>🔧 BLE Dongle v2 配置</h1>

<!-- 模式选择 -->
<div class="card">
  <h2>🎛 设备工作模式</h2>
  <div class="tab-bar" id="modeTabs">
    <div class="tab act" data-mode="0" onclick="switchMode(0)">📡 扫描器</div>
    <div class="tab" data-mode="1" onclick="switchMode(1)">📢 模拟广播</div>
    <div class="tab" data-mode="2" onclick="switchMode(2)">🔗 串口透传</div>
  </div>
  <p style="font-size:12px;color:#999;margin-top:4px">保存后重启设备将按所选模式运行。串口透传暂未实现。</p>
</div>

<!-- ====== 面板：扫描器 ====== -->
<div class="panel act" id="panel0">
<div class="card">
  <h2>📡 BLE 扫描参数</h2>
  <div class="form-row">
    <div class="form-group"><label>扫描间隔 (0.625ms)</label><input type="number" id="si" value="100" min="4" max="16384"><div class="hint">默认 100 (≈62.5ms)</div></div>
    <div class="form-group"><label>扫描窗口 (0.625ms)</label><input type="number" id="sw" value="99" min="4" max="16384"><div class="hint">&le; 扫描间隔</div></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>扫描类型</label><select id="st"><option value="0">被动扫描</option><option value="1" selected>主动扫描</option></select></div>
    <div class="form-group"><label>过滤重复</label><select id="sd"><option value="0" selected>不过滤</option><option value="1">过滤重复</option></select></div>
  </div>
</div>

<!-- ====== 高级选项：自定义输出格式 ====== -->
<div class="card" id="advOptCard">
  <h2 style="cursor:pointer;user-select:none" onclick="toggleAdvOpt()">⚙ 高级选项：自定义输出格式 <span id="advArrow" style="font-size:12px;color:#999;margin-left:8px">▼ 展开</span></h2>
  <div id="advOptBody" style="display:none">
    <p style="font-size:12px;color:#888;margin-bottom:12px">
      使用占位符自定义串口输出格式。可用标识：<br>
      <b>开始扫描</b>: <code>&lt;duration&gt;</code><br>
      <b>扫描结果</b>: <code>&lt;mac&gt;</code> <code>&lt;rssi&gt;</code> <code>&lt;addr&gt;</code> <code>&lt;name&gt;</code> <code>&lt;manuf&gt;</code> <code>&lt;uuid&gt;</code><br>
      <b>扫描结束</b>: <code>&lt;total&gt;</code> <code>&lt;matched&gt;</code><br>
      留空 = 不输出该行。非法占位符（如扫描开始中使用 <code>&lt;mac&gt;</code>）将原样打印，不会被替换。
    </p>

    <div class="form-group" style="margin-bottom:10px">
      <label>📤 扫描开始输出格式</label>
      <input type="text" id="sfStart" style="font-family:monospace;font-size:12px" placeholder="$SCAN_START|DURATION:<duration>">
      <div class="hint">占位符：<code>&lt;duration&gt;</code>（扫描持续秒数）。留空=不输出</div>
    </div>

    <div class="form-group" style="margin-bottom:10px">
      <label>📋 扫描结果输出格式</label>
      <input type="text" id="sfResult" style="font-family:monospace;font-size:12px" placeholder="$BLE|MAC:<mac>|RSSI:<rssi>|ADDR:<addr>|NAME:<name>|MANUF:<manuf>|UUID:<uuid>">
      <div class="hint">占位符：<code>&lt;mac&gt;</code> <code>&lt;rssi&gt;</code> <code>&lt;addr&gt;</code> <code>&lt;name&gt;</code> <code>&lt;manuf&gt;</code> <code>&lt;uuid&gt;</code></div>
    </div>

    <div class="form-group" style="margin-bottom:10px">
      <label>📥 扫描结束输出格式</label>
      <input type="text" id="sfEnd" style="font-family:monospace;font-size:12px" placeholder="$SCAN_END|TOTAL:<total>|MATCHED:<matched>">
      <div class="hint">占位符：<code>&lt;total&gt;</code> <code>&lt;matched&gt;</code>。留空=不输出</div>
    </div>

    <div style="margin-top:8px">
      <button class="btn btn-sm" style="background:#888" onclick="resetScanFormat()">🔄 恢复默认格式</button>
      <button class="btn btn-sm" style="background:#888;margin-left:8px" onclick="clearScanFormat()">🗑 全部清空</button>
    </div>

    <div id="sfWarn" style="margin-top:10px"></div>
  </div>
</div>

<div class="card">
  <h2>📋 白名单规则</h2>
  <div class="form-row">
    <div class="form-group" style="flex:0.7"><label>类型</label><select id="ft"><option value="0">MAC 地址</option><option value="1">广播名称</option><option value="2">厂商 ID</option></select></div>
    <div class="form-group" id="vg" style="flex:1.3"><label>值</label><input type="text" id="fv" placeholder="AA:BB:CC:DD:EE:FF"></div>
    <div class="form-group" id="cg" style="display:none;flex:0.8"><label>厂商 ID（HEX）</label><input type="text" id="ci" placeholder="0059" maxlength="6"><div class="hint">如 0059、4C00</div></div>
  </div>
  <button class="btn btn-primary" onclick="addEntry()">➕ 添加规则</button>
  <table><thead><tr><th>类型</th><th>值</th><th>状态</th><th>操作</th></tr></thead>
    <tbody id="wt"><tr><td colspan="4" class="empty">暂无白名单规则</td></tr></tbody></table>
</div>
</div>

<!-- ====== 面板：模拟广播 ====== -->
<div class="panel" id="panel1">
<div class="card">
  <h2>📢 广播参数</h2>
  <div class="form-row">
    <div class="form-group"><label>自定义 MAC</label><input type="text" id="am" placeholder="留空=默认 MAC"><div class="hint">格式 6 对 HEX。第一个字节 bit0 必须=0（单播）。最后一个字节 bit7-6 必须=0（Public）；非 0 也可，会启用随机地址</div></div>
    <div class="form-group"><label>广播类型</label><select id="at"><option value="0">ADV_IND（可连接）</option><option value="2">ADV_SCAN_IND</option><option value="3">ADV_NONCONN_IND</option></select></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>最小广播间隔 (0.625ms)</label><input type="number" id="ai_min" value="100" min="20" max="4000"><div class="hint">范围 20~4000，即 12.5ms~2.5s</div></div>
    <div class="form-group"><label>最大广播间隔 (0.625ms)</label><input type="number" id="ai_max" value="100" min="20" max="4000"><div class="hint">必须 ≥ 最小间隔</div></div>
  </div>
  <div class="form-row">
    <div class="form-group"><label>发射功率</label><select id="ap"><option value="-12">-12 dBm</option><option value="-9">-9 dBm</option><option value="-6">-6 dBm</option><option value="-3">-3 dBm</option><option value="0" selected>0 dBm</option><option value="3">3 dBm</option><option value="6">6 dBm</option><option value="9">9 dBm</option></select></div>
    <div class="form-group"><label>广播信道</label>
      <div style="display:flex;gap:12px;align-items:center;padding-top:4px">
        <label style="display:flex;align-items:center;gap:4px;font-size:13px;font-weight:400;color:#333"><input type="checkbox" id="ch37" checked onchange="onChToggle()"> CH37</label>
        <label style="display:flex;align-items:center;gap:4px;font-size:13px;font-weight:400;color:#333"><input type="checkbox" id="ch38" checked onchange="onChToggle()"> CH38</label>
        <label style="display:flex;align-items:center;gap:4px;font-size:13px;font-weight:400;color:#333"><input type="checkbox" id="ch39" checked onchange="onChToggle()"> CH39</label>
      </div>
    </div>
  </div>
  <input type="hidden" id="ach" value="7">
  <div class="form-row"><div class="form-group"><label>广播时长（秒）</label><input type="number" id="ad" value="0" min="0" max="3600"><div class="hint">0=持续广播</div></div></div>
</div>

<div class="card">
  <h2>📦 广播数据包构建</h2>
  <p style="font-size:12px;color:#666;margin-bottom:10px">每条 AD Structure = 类型 + 数据，自动拼成 HEX。<b>总长度 ≤ 31 字节</b>。</p>
  <div class="bar" id="lenBar">📏 当前总长度：<b>0</b> / 31 字节</div>

  <!-- Tab：可视化 vs 原始 -->
  <div class="tab-bar" id="advTabBar" style="margin:12px 0 4px">
    <div class="tab act" data-atab="0" onclick="switchAdvTab(0)">🧩 可视化构建</div>
    <div class="tab" data-atab="1" onclick="switchAdvTab(1)">📝 原始 HEX</div>
  </div>

  <!-- 可视化模式 -->
  <div id="advVis" class="panel act">
    <div class="form-row">
      <div class="form-group" style="flex:1.5"><label>AD Type</label><select id="adt"><option value="01">0x01 Flags</option><option value="03">0x03 16-bit UUID 完整</option><option value="09">0x09 完整名称</option><option value="08">0x08 短名称</option><option value="FF" selected>0xFF 厂商数据</option><option value="0A">0x0A 发射功率</option><option value="16">0x16 Service Data</option><option value="19">0x19 Appearance</option></select></div>
      <div class="form-group" style="flex:2.5"><label>数据（HEX）</label><input type="text" id="advv" placeholder="Flags 如 06 / 厂商如 4C0001 / 名称用 ASCII 自动转"></div>
    </div>
    <div class="form-row" id="nameAsciiRow" style="display:none">
      <div class="form-group" style="flex:2"><label>名称（ASCII）</label><input type="text" id="advName" placeholder="设备名称"><div class="hint">自动转 HEX</div></div>
    </div>
    <button class="btn btn-primary btn-sm" onclick="addAdStruct()">➕ 添加到数据包</button>

    <!-- 已添加的 AD 结构列表 -->
    <table style="margin-top:10px"><thead><tr><th>AD Type</th><th>HEX</th><th>大小</th><th>操作</th></tr></thead>
      <tbody id="adList"><tr><td colspan="4" class="empty">暂未添加 AD 结构</td></tr></tbody></table>
  </div>

  <!-- 原始 HEX 模式 -->
  <div id="advRaw" class="panel">
    <div class="form-group" style="flex:2"><label>完整 AdvData（HEX）</label><input type="text" id="ahr" placeholder="如 02010603034C00"><div class="hint">切换到原始模式时自动同步可视化数据，也可直接编辑</div></div>
    <div class="bar" id="rawLenBar" style="display:none">📏 原始 HEX 长度：<b>0</b> / 62 字符 (31 字节)</div>
  </div>
</div>

<div class="card" id="scanRespCard">
  <h2 style="cursor:pointer;user-select:none" onclick="toggleSrOpt()">📋 扫描响应数据 <span style="font-size:12px;color:#999;margin-left:6px">（高级选项，点击展开）</span> <span id="srArrow" style="font-size:12px;color:#999">▶</span></h2>
  <div id="srOptBody" style="display:none">
  <p style="font-size:12px;color:#666;margin-bottom:10px">同上，<b>总长度 ≤ 31 字节</b></p>
  <div class="bar" id="srLenBar">📏 当前总长度：<b>0</b> / 31 字节</div>
  <div class="tab-bar" id="srTabBar" style="margin:12px 0 4px">
    <div class="tab act" data-stab="0" onclick="switchSrTab(0)">🧩 可视化构建</div>
    <div class="tab" data-stab="1" onclick="switchSrTab(1)">📝 原始 HEX</div>
  </div>
  <div id="srVis" class="panel act">
    <div class="form-row">
      <div class="form-group" style="flex:1.5"><label>AD Type</label><select id="srt"><option value="09">0x09 完整名称</option><option value="08">0x08 短名称</option><option value="FF" selected>0xFF 厂商数据</option><option value="0A">0x0A 发射功率</option><option value="16">0x16 Service Data</option></select></div>
      <div class="form-group" style="flex:2.5"><label>数据（HEX）</label><input type="text" id="srv" placeholder="如 4C0001"></div>
    </div>
    <div class="form-row" id="srNameAsciiRow" style="display:none">
      <div class="form-group" style="flex:2"><label>名称（ASCII）</label><input type="text" id="srName" placeholder="设备名称"></div>
    </div>
    <button class="btn btn-primary btn-sm" onclick="addSrStruct()">➕ 添加到扫描响应</button>
    <table style="margin-top:10px"><thead><tr><th>AD Type</th><th>HEX</th><th>大小</th><th>操作</th></tr></thead>
      <tbody id="srList"><tr><td colspan="4" class="empty">暂未添加 AD 结构</td></tr></tbody></table>
  </div>
  <div id="srRaw" class="panel">
    <div class="form-group" style="flex:2"><label>完整 ScanRspData（HEX）</label><input type="text" id="asr" placeholder="可选"><div class="hint">切换到原始模式时自动同步可视化数据，也可直接编辑</div></div>
  </div>
  </div><!-- /srOptBody -->
</div>
</div>

<!-- ====== 面板：串口透传 ====== -->
<div class="panel" id="panel2">
<div class="card"><h2>🔗 串口透传</h2><p style="color:#999;text-align:center;padding:32px">功能开发中，敬请期待...</p></div>
</div>

<!-- ====== 底部按钮 ====== -->
<div class="card"><div class="action-bar">
  <button class="btn btn-success" onclick="saveAll()">💾 保存全部配置</button>
  <button class="btn" style="background:#673ab7" onclick="exportConfig()">📥 导出配置 JSON</button>
  <button class="btn" style="background:#f9ab00;color:#333" onclick="importConfig()">📤 导入配置 JSON</button>
  <button class="btn btn-danger" onclick="reboot()">🔄 重启设备</button>
</div></div>
<input type="file" id="importFileInput" accept=".json" style="display:none" onchange="onImportFileSelected(event)">

<script>
var W=[],M=0;
// 广告数据包：可视化模式
var AdS=[], SrS=[];
// 当前模式：0=可视化, 1=原始
var AdvMode=0, SrMode=0;

// 信道多选 → 位掩码；至少选一个
function onChToggle(){
  var c37=document.getElementById('ch37');
  var c38=document.getElementById('ch38');
  var c39=document.getElementById('ch39');
  var v=0;
  if(c37.checked)v|=1;
  if(c38.checked)v|=2;
  if(c39.checked)v|=4;
  if(v===0){
    // 恢复触发事件的 checkbox 状态并提示
    alert('至少选择一个广播信道');
    // 找出是哪个被取消了
    if(!c37.checked && !c38.checked && !c39.checked){
      // 三个都取消不可能，因为至少有一个在触发前是选中的；重新计算
      // 用 setChannelMapFromMask 恢复到上次有效值
      var oldV=parseInt(document.getElementById('ach').value)||7;
      setChannelMapFromMask(oldV);
    }
    return;
  }
  document.getElementById('ach').value=v;
}

// 位掩码 → 恢复 checkbox
function setChannelMapFromMask(mask){
  document.getElementById('ch37').checked=(mask&1)!==0;
  document.getElementById('ch38').checked=(mask&2)!==0;
  document.getElementById('ch39').checked=(mask&4)!==0;
  document.getElementById('ach').value=mask;
}

function switchMode(m){M=m;document.querySelectorAll('#modeTabs .tab').forEach(function(t){t.classList.remove('act')});['panel0','panel1','panel2'].forEach(function(id){var el=document.getElementById(id);if(el)el.classList.remove('act')});document.querySelector('#modeTabs .tab[data-mode="'+m+'"]').classList.add('act');var p=document.getElementById('panel'+m);if(p)p.classList.add('act')}

function switchAdvTab(m){AdvMode=m;document.querySelectorAll('#advTabBar .tab').forEach(function(t,i){t.classList.toggle('act',i===m)});document.getElementById('advVis').style.display=m===0?'block':'none';document.getElementById('advRaw').style.display=m===1?'block':'none';if(m===1)document.getElementById('ahr').value=calcAdvHex()}

function switchSrTab(m){SrMode=m;document.querySelectorAll('#srTabBar .tab').forEach(function(t,i){t.classList.toggle('act',i===m)});document.getElementById('srVis').style.display=m===0?'block':'none';document.getElementById('srRaw').style.display=m===1?'block':'none';if(m===1)document.getElementById('asr').value=calcSrHex()}

// 动态 AD Type 列表
var AdNames={'01':'Flags','03':'16-bit UUID','09':'完整名称','08':'短名称','FF':'厂商数据','0A':'发射功率','16':'Service Data','19':'Appearance'};

// 将 HEX 字符串解析为 AD 结构数组（按 BLE AD Structure 格式：Length,Type,Data）
function parseHexToStructs(hex){
  var h=hex.replace(/[\s:]/g,'').toUpperCase();
  if(!h||h.length%2!==0) return {ok:false,error:'📏 HEX 长度不是偶数位，无法解析'};
  var pos=0,list=[];
  while(pos<h.length){
    if(pos+4>h.length){return {ok:false,error:'⚠ 断尾数据 @'+pos+': 不足 4 个 HEX 字符'};}
    var len=parseInt(h.substr(pos,2),16);   // 第一个字节 = AD Structure 的 Length 字段
    if(len<1){return {ok:false,error:'⚠ AD Structure @'+pos+': Length='+len+' 无效'}}
    var totalHexChars=2+len*2;  // Length(2) + (Type+Data) * 2
    if(pos+totalHexChars>h.length){return {ok:false,error:'⚠ AD Structure @'+pos+': 声明 '+len+'B，剩余数据不足'}}
    var seg=h.substring(pos,pos+totalHexChars);
    var type=h.substr(pos+2,2);
    var name=AdNames[type]||'0x'+type;
    list.push({type:type,name:name,hex:seg,size:len+1});
    pos+=totalHexChars;
  }
  return {ok:true,list:list};
}

// 计算 HEX 长度（字节数 = HEX字符数/2）
function hexBytes(h){return h.length/2}

// 更新长度提示条
function updateLenBars(){
  var a=calcAdvHex(); var aB=hexBytes(a);
  var b=document.getElementById('lenBar'); b.innerHTML='📏 当前总长度：<b>'+aB+'</b> / 31 字节';
  b.className='bar'+(aB>31?' err':aB>27?' warn':'');
  if(aB>31) b.innerHTML+=' <b style="color:#b30000">⚠ 超限!</b>';

  var s=calcSrHex(); var sB=hexBytes(s);
  var sb=document.getElementById('srLenBar'); sb.innerHTML='📏 当前总长度：<b>'+sB+'</b> / 31 字节';
  sb.className='bar'+(sB>31?' err':sB>27?' warn':'');
  if(sB>31) sb.innerHTML+=' <b style="color:#b30000">⚠ 超限!</b>';

  var r=document.getElementById('ahr').value.trim();
  if(r){var rb=hexBytes(r);var rlb=document.getElementById('rawLenBar');rlb.style.display='block';rlb.innerHTML='📏 原始 HEX 长度：<b>'+rb+'</b> / 62 字符 (31 字节)';rlb.className='bar'+(rb>31?' err':rb>27?' warn':'');}
}

// 可视化模式：拼接所有 AD 结构
function calcAdvHex(){
  var h='';
  for(var i=0;i<AdS.length;i++){var s=AdS[i]; h+=s.hex}
  return h.toUpperCase()
}

function calcSrHex(){
  var h='';
  for(var i=0;i<SrS.length;i++){var s=SrS[i]; h+=s.hex}
  return h.toUpperCase()
}

// 获取最终的 AdvData HEX
function getAdvHex(){
  if(AdvMode===1) return document.getElementById('ahr').value.replace(/[\s:]/g,'').toUpperCase();
  return calcAdvHex()
}

function getSrHex(){
  if(SrMode===1) return document.getElementById('asr').value.replace(/[\s:]/g,'').toUpperCase();
  return calcSrHex()
}

// 添加一条 AD 结构
function addAdStruct(){
  var t=document.getElementById('adt').value;
  var v;
  if(t==='09'||t==='08'){
    // 名称类型：可输入 ASCII
    var nm=document.getElementById('advName').value.trim();
    if(!nm){alert('请输入名称');return}
    v=''; for(var i=0;i<nm.length;i++){var c=nm.charCodeAt(i).toString(16); v+=(c.length<2?'0':'')+c}
  } else {
    v=document.getElementById('advv').value.replace(/[\s:]/g,'').toUpperCase();
    if(!v||v.length%2!==0){alert('请输入有效的 HEX 数据（偶数位）');return}
  }
  // 构建标准 AD Structure：Length(1B) + Type(1B) + Data
  var dataLen=v.length/2;      // 数据部分字节数
  var totalLen=dataLen+1;       // Length = 数据 + 1(Type 字节)
  var lenHex=(totalLen<16?'0':'')+totalLen.toString(16);
  var h=lenHex+t+v;
  var b=h.length/2;
  if(hexBytes(getAdvHex())+b>31){alert('添加此项后总长度将超过 31 字节！');return}
  var entry={type:t,name:AdNames[t]||t,hex:h,size:b};
  AdS.push(entry);
  renderAdList();
  updateLenBars();
  document.getElementById('advv').value='';
  document.getElementById('advName').value='';
}

function addSrStruct(){
  var t=document.getElementById('srt').value;
  var v;
  if(t==='09'||t==='08'){
    var nm=document.getElementById('srName').value.trim();
    if(!nm){alert('请输入名称');return}
    v=''; for(var i=0;i<nm.length;i++){var c=nm.charCodeAt(i).toString(16); v+=(c.length<2?'0':'')+c}
  } else {
    v=document.getElementById('srv').value.replace(/[\s:]/g,'').toUpperCase();
    if(!v||v.length%2!==0){alert('请输入有效的 HEX 数据（偶数位）');return}
  }
  var dataLen=v.length/2;
  var totalLen=dataLen+1;
  var lenHex=(totalLen<16?'0':'')+totalLen.toString(16);
  var h=lenHex+t+v;
  var b=h.length/2;
  if(hexBytes(getSrHex())+b>31){alert('添加此项后总长度将超过 31 字节！');return}
  SrS.push({type:t,name:AdNames[t]||t,hex:h,size:b});
  renderSrList();
  updateLenBars();
  document.getElementById('srv').value='';
  document.getElementById('srName').value='';
}

function deleteAdEntry(i){AdS.splice(i,1);renderAdList();updateLenBars()}
function deleteSrEntry(i){SrS.splice(i,1);renderSrList();updateLenBars()}

function renderAdList(){
  var tb=document.getElementById('adList');
  if(!AdS.length){tb.innerHTML='<tr><td colspan="4" class="empty">暂未添加 AD 结构</td></tr>';return}
  var h='';
  for(var i=0;i<AdS.length;i++){var e=AdS[i];h+='<tr class="drag" draggable="true" data-idx="'+i+'" data-kind="ad"><td><span class="drag-icon">⠿</span><span class="tag">0x'+e.type+' '+e.name+'</span></td><td><code>'+e.hex+'</code></td><td>'+e.size+'B</td><td><button class="btn btn-danger btn-sm" onclick="deleteAdEntry('+i+')">删除</button></td></tr>'}
  tb.innerHTML=h;
}

function renderSrList(){
  var tb=document.getElementById('srList');
  if(!SrS.length){tb.innerHTML='<tr><td colspan="4" class="empty">暂未添加 AD 结构</td></tr>';return}
  var h='';
  for(var i=0;i<SrS.length;i++){var e=SrS[i];h+='<tr class="drag" draggable="true" data-idx="'+i+'" data-kind="sr"><td><span class="drag-icon">⠿</span><span class="tag">0x'+e.type+' '+e.name+'</span></td><td><code>'+e.hex+'</code></td><td>'+e.size+'B</td><td><button class="btn btn-danger btn-sm" onclick="deleteSrEntry('+i+')">删除</button></td></tr>'}
  tb.innerHTML=h;
}

// 校验 MAC 地址
function validateMac(mac){
  if(!mac) return null;
  var m=mac.toUpperCase().trim();
  if(!/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/.test(m)) return 'MAC 格式错误，应为 AA:BB:CC:DD:EE:FF';
  var parts=m.split(':');
  // 第一个字节 bit0 = unicast/multicast, bit1 = universal/local
  var firstByte=parseInt(parts[0],16);
  if(firstByte&1) return '第一个字节 '+parts[0]+' 的 bit0=1（多播地址），必须是单播地址（bit0=0）';
  // 最后一个字节 bit7-6 = 00 才是 public 地址
  var lastByte=parseInt(parts[5],16);
  if((lastByte&0xC0)!==0) return '最后一个字节 '+parts[5]+' 最高2位不为 00，非 Public 地址。可设如 00,04,08...';
  return null;
}
function validateInterval(v){
  if(v<20||v>4000) return '广播间隔范围 20~4000 (12.5ms~2.5s)';
  return null;
}

function loadConfig(){
  fetch('/api/config').then(function(r){return r.json()}).then(function(d){
    W=d.whitelist||[];renderTable();
    var dm=d.deviceMode!==undefined?d.deviceMode:0;M=dm;switchMode(dm);
    var sp=d.scanParams||{};
    document.getElementById('si').value=sp.scanInterval||100;
    document.getElementById('sw').value=sp.scanWindow||99;
    document.getElementById('st').value=sp.scanType||1;
    document.getElementById('sd').value=sp.scanDuplicate?1:0;
    var ap=d.advConfig||{};
    document.getElementById('am').value=ap.customMac||'';
    document.getElementById('ap').value=ap.txPower||0;
    document.getElementById('ai_min').value=ap.advIntervalMin||100;
    document.getElementById('ai_max').value=ap.advIntervalMax||100;
    document.getElementById('ad').value=ap.advDuration||0;
    document.getElementById('at').value=ap.advType||0;
    setChannelMapFromMask(ap.channelMap!==undefined?ap.channelMap:7);
    // 智能解析加载的 HEX
    if(ap.advDataHex){
      var parsed=parseHexToStructs(ap.advDataHex);
      if(parsed.ok){AdS=parsed.list;renderAdList();updateLenBars()}
      else{AdS=[];renderAdList();document.getElementById('lenBar').innerHTML=parsed.error;document.getElementById('lenBar').className='bar err'}
      document.getElementById('ahr').value=ap.advDataHex;
    }
    if(ap.scanRespHex){
      var parsedS=parseHexToStructs(ap.scanRespHex);
      if(parsedS.ok){SrS=parsedS.list;renderSrList();updateLenBars()}
      else{SrS=[];renderSrList();document.getElementById('srLenBar').innerHTML=parsedS.error;document.getElementById('srLenBar').className='bar err'}
      document.getElementById('asr').value=ap.scanRespHex;
    }
    // 触发联动（不插入默认 Flag）
    loadScanFormat();  // 加载输出格式
  });
}

function renderTable(){
  var tb=document.getElementById('wt');
  if(!W.length){tb.innerHTML='<tr><td colspan="4" class="empty">暂无白名单规则</td></tr>';return}
  var L=['MAC','名称','厂商'],C=['t0','t1','t2'],h='';
  for(var i=0;i<W.length;i++){
    var e=W[i],v=e.type===2?'0x'+('0000'+e.companyId.toString(16).toUpperCase()).slice(-4):e.value;
    h+='<tr><td><span class="tag '+(C[e.type]||'')+'">'+(L[e.type]||'')+'</span></td><td>'+v+'</td><td>'+(e.enabled?'✅':'❌')+'</td><td><button class="btn btn-danger btn-sm" onclick="deleteEntry('+i+')">删除</button></td></tr>';
  }
  tb.innerHTML=h;
}

function addEntry(){
  var t=parseInt(document.getElementById('ft').value),v=document.getElementById('fv').value.trim(),c=document.getElementById('ci').value.trim();
  if(t===2){
    // 厂商 ID：必须 1~4 位有效 HEX，范围 0x0000~0xFFFF
    if(!c){alert('请输入厂商 ID（HEX）');return}
    if(!/^[0-9A-Fa-f]{1,4}$/.test(c)){alert('厂商 ID 必须是 1~4 位 HEX 字符（如 0059、4C00）');return}
    var cid=parseInt(c,16);
    if(isNaN(cid)||cid<0||cid>65535){alert('厂商 ID 无效，范围 0x0000~0xFFFF');return}
    W.push({type:t,value:"",companyId:cid,enabled:true})
  }
  else if(t===0){
    // MAC 地址：校验格式 AA:BB:CC:DD:EE:FF
    var m=v.toUpperCase();
    if(!/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/.test(m)){alert('MAC 格式错误，应为 AA:BB:CC:DD:EE:FF');return}
    W.push({type:t,value:m,companyId:0,enabled:true})
  }
  else{
    // 广播名称
    if(!v){alert('请输入广播名称');return}
    W.push({type:t,value:v,companyId:0,enabled:true})
  }
  renderTable();document.getElementById('fv').value='';document.getElementById('ci').value='';
}

function deleteEntry(i){W.splice(i,1);renderTable()}

function saveAll(){
  // ====== 扫描参数校验 ======
  var si=parseInt(document.getElementById('si').value)||100;
  var sw=parseInt(document.getElementById('sw').value)||99;
  if(isNaN(si)||si<4||si>16384){alert('❌ 扫描间隔范围 4~16384 (×0.625ms)');return}
  if(isNaN(sw)||sw<4||sw>16384){alert('❌ 扫描窗口范围 4~16384 (×0.625ms)');return}
  if(sw>si){alert('❌ 扫描窗口 ('+sw+') 必须 ≤ 扫描间隔 ('+si+')');return}

  // ====== 扫描输出格式校验 ======
  if(!validateScanFormat()) return;

  // ====== 广播 MAC 校验 ======
  var mac=document.getElementById('am').value.trim();
  var macErr=validateMac(mac);
  if(macErr){alert('❌ MAC 地址错误：\n'+macErr);return}

  // ====== 广播间隔校验 ======
  var minInt=parseInt(document.getElementById('ai_min').value)||100;
  var maxInt=parseInt(document.getElementById('ai_max').value)||100;
  if(minInt<20||minInt>4000||maxInt<20||maxInt>4000){alert('❌ 广播间隔范围 20~4000');return}
  if(maxInt<minInt){alert('❌ 最大间隔必须 ≥ 最小间隔');return}
  // 校验广播数据长度
  var ah=getAdvHex(); var aB=hexBytes(ah);
  if(aB>31){alert('❌ 广播数据长度为 '+aB+' 字节，超过 31 字节限制！\n请删除一些 AD 结构或缩短数据。');return}
  var as_x=getSrHex(); var aS=hexBytes(as_x);
  if(aS>31){alert('❌ 扫描响应数据长度为 '+aS+' 字节，超过 31 字节限制！');return}

  var sp={scanInterval:parseInt(document.getElementById('si').value)||100,scanWindow:parseInt(document.getElementById('sw').value)||99,scanType:parseInt(document.getElementById('st').value)||1,scanDuplicate:document.getElementById('sd').value==='1',ownAddrType:0,scanFilterPolicy:0};
  var sf={scanStartFmt:document.getElementById('sfStart').value.trim(),scanResultFmt:document.getElementById('sfResult').value.trim(),scanEndFmt:document.getElementById('sfEnd').value.trim()};
  var ap={customMac:mac,advDataHex:ah,scanRespHex:as_x,txPower:parseInt(document.getElementById('ap').value)||0,advIntervalMin:minInt,advIntervalMax:maxInt,advDuration:parseInt(document.getElementById('ad').value)||0,advType:parseInt(document.getElementById('at').value)||0,channelMap:parseInt(document.getElementById('ach').value)||7};
  var payload={deviceMode:M,whitelist:W,scanParams:sp,scanFormat:sf,advConfig:ap};
  fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.json()}).then(function(){alert('✅ 保存成功，重启后生效')}).catch(function(){alert('❌ 保存失败')});
}

// ========== 高级选项：自定义输出格式 ==========

// 默认格式（用户友好占位符版本）
var DEFS={
  s:'$SCAN_START|DURATION:<duration>',
  r:'$BLE|MAC:<mac>|RSSI:<rssi>|ADDR:<addr>|NAME:<name>|MANUF:<manuf>|UUID:<uuid>',
  e:'$SCAN_END|TOTAL:<total>|MATCHED:<matched>'
};

function toggleAdvOpt(){
  var b=document.getElementById('advOptBody');
  var a=document.getElementById('advArrow');
  if(b.style.display==='none'){
    b.style.display='block';a.innerHTML='▲ 收起';
  }else{
    b.style.display='none';a.innerHTML='▼ 展开';
  }
}

// 从 API 加载 scanFormat
function loadScanFormat(){
  fetch('/api/scanformat').then(function(r){return r.json()}).then(function(d){
    document.getElementById('sfStart').value=d.scanStartFmt||'';
    document.getElementById('sfResult').value=d.scanResultFmt||'';
    document.getElementById('sfEnd').value=d.scanEndFmt||'';
  });
}

function resetScanFormat(){
  document.getElementById('sfStart').value=DEFS.s;
  document.getElementById('sfResult').value=DEFS.r;
  document.getElementById('sfEnd').value=DEFS.e;
}

function clearScanFormat(){
  document.getElementById('sfStart').value='';
  document.getElementById('sfResult').value='';
  document.getElementById('sfEnd').value='';
}

// 校验扫描输出格式（在 saveAll 中调用）
function validateScanFormat(){
  var startFmt=document.getElementById('sfStart').value.trim();
  var resultFmt=document.getElementById('sfResult').value.trim();
  var endFmt=document.getElementById('sfEnd').value.trim();
  var warns=[],div=document.getElementById('sfWarn');
  div.innerHTML='';

  // 扫描结果为空 → 需要确认
  if(!resultFmt){
    if(!confirm('⚠ 当前"扫描结果输出格式"为空，保存后扫描将<b>不会输出任何设备信息</b>。\n\n确定要这样保存吗？')) return false;
  }

  // 检测非法占位符（不在允许列表中的 <xxx> 标签）
  // scanStart 只允许 <duration>
  var invalidStart=detectInvalidPlaceholders(startFmt,['duration']);
  if(invalidStart.length>0){
    var w='⚠ 开始扫描文本中检测到无效占位符：'+invalidStart.join(',')+'<br>这些标签将<b>原样打印</b>，不会被替换为实际值。<br>仅允许：&lt;duration&gt;';
    warns.push(w);
  }

  // scanEnd 只允许 <total> <matched>
  var invalidEnd=detectInvalidPlaceholders(endFmt,['total','matched']);
  if(invalidEnd.length>0){
    var w='⚠ 结束扫描文本中检测到无效占位符：'+invalidEnd.join(',')+'<br>这些标签将<b>原样打印</b>，不会被替换为实际值。<br>仅允许：&lt;total&gt; &lt;matched&gt;';
    warns.push(w);
  }

  // scanResult 检查有效占位符是否都在
  var validR=['mac','rssi','addr','name','manuf','uuid'];
  var invalidR=detectInvalidPlaceholders(resultFmt,validR);
  if(invalidR.length>0){
    var w='⚠ 扫描结果文本中检测到无效占位符：'+invalidR.join(',')+'<br>这些标签将<b>原样打印</b>。有效占位符：'+validR.map(function(v){return '&lt;'+v+'&gt;'}).join(', ');
    warns.push(w);
  }

  if(warns.length>0){
    div.innerHTML='<div class="bar warn">'+warns.join('</div><div class="bar warn" style="margin-top:4px">')+'</div>';
    return true; // 警告但不阻止保存
  }
  return true;
}

// 检测文本中不在白名单中的 <xxx> 占位符
function detectInvalidPlaceholders(text,validList){
  var re=/<(\w+)>/g,m,invalid=[];
  while((m=re.exec(text))!==null){
    if(validList.indexOf(m[1])===-1 && invalid.indexOf(m[1])===-1){
      invalid.push('&lt;'+m[1]+'&gt;');
    }
  }
  return invalid;
}

// 扫描响应数据折叠/展开
function toggleSrOpt(){
  var b=document.getElementById('srOptBody');
  var a=document.getElementById('srArrow');
  if(b.style.display==='none'){
    b.style.display='block';a.innerHTML='▲';
  }else{
    b.style.display='none';a.innerHTML='▶';
  }
}

// 导出配置 JSON 文件
function exportConfig(){
  var btn=document.querySelector('button[onclick="exportConfig()"]');
  if(!btn) return;
  var origText=btn.innerHTML;
  btn.innerHTML='⏳ 正在从设备获取配置...';
  btn.disabled=true;
  btn.style.opacity='0.7';
  fetch('/api/config').then(function(r){
    if(!r.ok) throw new Error('HTTP '+r.status);
    return r.json();
  }).then(function(d){
    var blob=new Blob([JSON.stringify(d,null,2)],{type:'application/json'});
    var url=URL.createObjectURL(blob);
    var a=document.createElement('a');
    a.href=url;a.download='ble_dongle_config.json';
    document.body.appendChild(a);a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }).catch(function(e){
    alert('❌ 导出失败：'+e.message);
  }).finally(function(){
    btn.innerHTML=origText;
    btn.disabled=false;
    btn.style.opacity='1';
  });
}

// 导入配置 JSON：点击按钮 → 弹出文件选择
function importConfig(){
  document.getElementById('importFileInput').click();
}

// 文件选择后的回调
function onImportFileSelected(event){
  var file=event.target.files[0];
  if(!file) return;
  if(!confirm('⚠ 即将用所选文件覆盖设备当前全部配置。\n\n确定要继续吗？')){event.target.value='';return}

  var btn=document.querySelector('button[onclick="importConfig()"]');
  var origText=btn.innerHTML;
  btn.innerHTML='⏳ 正在上传并应用配置...';
  btn.disabled=true;
  btn.style.opacity='0.7';

  var reader=new FileReader();
  reader.onload=function(e){
    try{
      var json=JSON.parse(e.target.result);
      // 先在前端做基本校验（有 whitelist 或 scanParams 等字段）
      fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(json)})
      .then(function(r){return r.json()})
      .then(function(resp){
        alert('✅ 配置已导入并应用，重启后生效');
        // 刷新页面以加载新配置
        loadConfig();
      }).catch(function(err){
        alert('❌ 导入失败：'+err.message);
      }).finally(function(){
        btn.innerHTML=origText;
        btn.disabled=false;
        btn.style.opacity='1';
        event.target.value='';
      });
    }catch(err){
      alert('❌ JSON 文件格式无效：'+err.message);
      btn.innerHTML=origText;
      btn.disabled=false;
      btn.style.opacity='1';
      event.target.value='';
    }
  };
  reader.readAsText(file);
}

function reboot(){if(!confirm('确定重启设备？'))return;fetch('/api/reboot',{method:'POST'});alert('设备正在重启...')}

// 白名单类型切换
document.getElementById('ft').addEventListener('change',function(){var s=this.value==='2';document.getElementById('cg').style.display=s?'block':'none';document.getElementById('vg').style.display=s?'none':'block';if(!s)document.getElementById('fv').placeholder=this.value==='0'?'AA:BB:CC:DD:EE:FF':'广播名称'});

// AD Type 切换：名称类型显示 ASCII 输入框
document.getElementById('adt').addEventListener('change',function(){var n=this.value==='09'||this.value==='08';document.getElementById('nameAsciiRow').style.display=n?'block':'none';document.getElementById('advv').parentElement.style.display=n?'none':'block'});
document.getElementById('srt').addEventListener('change',function(){var n=this.value==='09'||this.value==='08';document.getElementById('srNameAsciiRow').style.display=n?'block':'none';document.getElementById('srv').parentElement.style.display=n?'none':'block'});

// 广播类型切换：不可连接/不可扫描类型禁用扫描响应卡片
document.getElementById('at').addEventListener('change',function(){var t=parseInt(this.value);var d=(t===3);var card=document.getElementById('scanRespCard');card.style.opacity=d?'0.5':'1';card.querySelectorAll('input,select,button').forEach(function(el){el.disabled=d});document.getElementById('srLenBar').style.display=d?'none':'flex'});

// 原始 HEX 输入时更新长度
document.getElementById('ahr').addEventListener('input',updateLenBars);
document.getElementById('asr').addEventListener('input',updateLenBars);

// ========== 拖拽排序 ==========
var dgSrc=null,dkSrc=null;
function initDrag(){
  ['adList','srList'].forEach(function(tbId){
    var tb=document.getElementById(tbId);
    if(!tb)return;
    tb.addEventListener('dragstart',function(e){
      var tr=e.target.closest('tr.drag');
      if(!tr)return;
      dgSrc=parseInt(tr.getAttribute('data-idx'));
      dkSrc=tr.getAttribute('data-kind');
      e.dataTransfer.effectAllowed='move';
      e.dataTransfer.setData('text/plain','');
      tr.style.opacity='0.5';
    });
    tb.addEventListener('dragend',function(e){
      var tr=e.target.closest('tr.drag');
      if(tr)tr.style.opacity='1';
      dgSrc=null;dkSrc=null;
      tb.querySelectorAll('tr').forEach(function(r){r.classList.remove('drag-over')});
    });
    tb.addEventListener('dragover',function(e){
      e.preventDefault();
      e.dataTransfer.dropEffect='move';
      var tr=e.target.closest('tr.drag');
      if(!tr)return;
      tb.querySelectorAll('tr').forEach(function(r){r.classList.remove('drag-over')});
      tr.classList.add('drag-over');
    });
    tb.addEventListener('drop',function(e){
      e.preventDefault();
      var tr=e.target.closest('tr.drag');
      if(!tr||dgSrc===null||dkSrc===null)return;
      var dstIdx=parseInt(tr.getAttribute('data-idx'));
      var dstKind=tr.getAttribute('data-kind');
      if(dkSrc!==dstKind)return;
      if(dgSrc===dstIdx)return;
      // 移动数组元素
      moveArrayItem(dkSrc,dgSrc,dstIdx);
      // 重新渲染
      if(dkSrc==='ad'){renderAdList();}
      else{renderSrList();}
      updateLenBars();
    });
    // 修复 tr 内 button 不触发 drag 的问题
    tb.addEventListener('dragleave',function(e){
      var tr=e.target.closest('tr.drag');
      if(tr)tr.classList.remove('drag-over');
    });
  });
}

function moveArrayItem(kind,fromIdx,toIdx){
  var arr=(kind==='ad')?AdS:SrS;
  var item=arr[fromIdx];
  arr.splice(fromIdx,1);
  arr.splice(toIdx,0,item);
}

window.addEventListener('DOMContentLoaded',function(){
  loadConfig();
  initDrag();
});
</script>
</body>
</html>

)rawliteral";

#endif // EMBEDDED_WEB_CONFIG_H
